site_name: My Docs
site_url: https://iheb-sahloul.github.io/my-docs/
site_author: Iheb Sahloul

repo_name: iheb-sahloul/my-docs
repo_url: https://github.com/iheb-sahloul/my-docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

plugins: 
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc

nav:
- Home: index.md
- Tech: 
  - Backend:
    - API guidelines: tech/backend/api-guidelines.md
    - Structure unit tests: tech/backend/aaa.md
    - Debugging a Java Stream in IntelliJ: tech/backend/java-stream-intellij.md 
    - Arch Unit: tech/backend/arch-unit.md
    - Java 25: tech/backend/java-25.md
  - Devops: 
    - My most used K8S commands: tech/devops/kubectl.md 
    - HELM: tech/devops/helm.md
  - Shell:
    - Text editing with sed: tech/shell/sed.md
    - Text searching with grep: tech/shell/grep.md
    - Text processing with awk: tech/shell/awk.md
    - Making HTTP requests with curl: tech/shell/curl.md
    - JSON processing with jq: tech/shell/jq.md
  - Tech debt: tech/tech-debt.md
- Architecture: 
  - Hexagonal Architecture: architecture/hexagonal.md
  - TOGAF:
    - Foundation:
      - Introduction and Concepts: architecture/togaf/foundation/unit1.md
      - Definitions: architecture/togaf/foundation/unit2.md
      - ADM Phases: architecture/togaf/foundation/unit3.md
      - ADM Techniques: architecture/togaf/foundation/unit4.md
      - Applying the ADM: architecture/togaf/foundation/unit5.md
      - Architecture Governance: architecture/togaf/foundation/unit6.md
      - Architecture Content: architecture/togaf/foundation/unit7.md
    - Practitioner:
      - Context for Enterprise Architecture: architecture/togaf/practitioner/unit1.md
      - Stakeholder Management: architecture/togaf/practitioner/unit2.md
      - Phase A, the Starting Point: architecture/togaf/practitioner/unit3.md
      - Architecture Development: architecture/togaf/practitioner/unit4.md
      - Implementing the Architecture: architecture/togaf/practitioner/unit5.md
      - Architecture Change Management: architecture/togaf/practitioner/unit6.md
      - Requirements Management: architecture/togaf/practitioner/unit7.md
      - Supporting the ADM Work: architecture/togaf/practitioner/unit8.md